<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Code-Analysis-P3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Code-Analysis-P3_files/libs/clipboard/clipboard.min.js"></script>
<script src="Code-Analysis-P3_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Code-Analysis-P3_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Code-Analysis-P3_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Code-Analysis-P3_files/libs/quarto-html/popper.min.js"></script>
<script src="Code-Analysis-P3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Code-Analysis-P3_files/libs/quarto-html/anchor.min.js"></script>
<link href="Code-Analysis-P3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Code-Analysis-P3_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Code-Analysis-P3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Code-Analysis-P3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Code-Analysis-P3_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Code-Analysis-P3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="approach" class="level2">
<h2 class="anchored" data-anchor-id="approach">Approach</h2>
<p>Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
</section>
<section id="working-with-kaggle-dataset" class="level2">
<h2 class="anchored" data-anchor-id="working-with-kaggle-dataset">Working with Kaggle dataset</h2>
<p><strong>Loading the raw kaggle data from Github</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#builtin raw data load</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>builtin_jobs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/meiqing39/607-Project-3/refs/heads/RamdeGuibril/builtin_jobs.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 11 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): job_title, company, industry, source, job_url, job_description
dbl (1): job_id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>builtin_job_skills <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/meiqing39/607-Project-3/refs/heads/RamdeGuibril/builtin_job_skills.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 46 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): skill
dbl (1): job_id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Kaggle data load###</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>kaggle_url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/meiqing39/607-Project-3/refs/heads/main/data_cleaned_2021.csv"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>kg <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(kaggle_url, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()   <span class="co"># &lt;- renames by snake_case format, removes special character</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Ensures consistent and reproducible references to variable by using janitor function clean_names()</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>kg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 742 × 42
   index job_title  salary_estimate job_description rating company_name location
   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;   
 1     0 Data Scie… $53K-$91K (Gla… "Data Scientis…    3.8 "Tecolote R… Albuque…
 2     1 Healthcar… $63K-$112K (Gl… "What You Will…    3.4 "University… Linthic…
 3     2 Data Scie… $80K-$90K (Gla… "KnowBe4, Inc.…    4.8 "KnowBe4\n4… Clearwa…
 4     3 Data Scie… $56K-$97K (Gla… "*Organization…    3.8 "PNNL\n3.8"  Richlan…
 5     4 Data Scie… $86K-$143K (Gl… "Data Scientis…    2.9 "Affinity S… New Yor…
 6     5 Data Scie… $71K-$119K (Gl… "CyrusOne is s…    3.4 "CyrusOne\n… Dallas,…
 7     6 Data Scie… $54K-$93K (Gla… "Job Descripti…    4.1 "ClearOne A… Baltimo…
 8     7 Data Scie… $86K-$142K (Gl… "Advanced Anal…    3.8 "Logic20/20… San Jos…
 9     8 Research … $38K-$84K (Gla… "SUMMARY\n\nTh…    3.3 "Rochester … Rochest…
10     9 Data Scie… $120K-$160K (G… "isn’t your us…    4.6 "&lt;intent&gt;\n… New Yor…
# ℹ 732 more rows
# ℹ 35 more variables: headquarters &lt;chr&gt;, size &lt;chr&gt;, founded &lt;dbl&gt;,
#   type_of_ownership &lt;chr&gt;, industry &lt;chr&gt;, sector &lt;chr&gt;, revenue &lt;chr&gt;,
#   competitors &lt;chr&gt;, hourly &lt;dbl&gt;, employer_provided &lt;dbl&gt;,
#   lower_salary &lt;dbl&gt;, upper_salary &lt;dbl&gt;, avg_salary_k &lt;dbl&gt;,
#   company_txt &lt;chr&gt;, job_location &lt;chr&gt;, age &lt;dbl&gt;, python &lt;dbl&gt;,
#   spark &lt;dbl&gt;, aws &lt;dbl&gt;, excel &lt;dbl&gt;, sql &lt;dbl&gt;, sas &lt;dbl&gt;, keras &lt;dbl&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(kg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "index"              "job_title"          "salary_estimate"   
 [4] "job_description"    "rating"             "company_name"      
 [7] "location"           "headquarters"       "size"              
[10] "founded"            "type_of_ownership"  "industry"          
[13] "sector"             "revenue"            "competitors"       
[16] "hourly"             "employer_provided"  "lower_salary"      
[19] "upper_salary"       "avg_salary_k"       "company_txt"       
[22] "job_location"       "age"                "python"            
[25] "spark"              "aws"                "excel"             
[28] "sql"                "sas"                "keras"             
[31] "pytorch"            "scikit"             "tensor"            
[34] "hadoop"             "tableau"            "bi"                
[37] "flink"              "mongo"              "google_an"         
[40] "job_title_sim"      "seniority_by_title" "degree"            </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#head(10)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Examine Data structure and initial inspection</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(kg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 742
Columns: 42
$ index              &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1…
$ job_title          &lt;chr&gt; "Data Scientist", "Healthcare Data Scientist", "Dat…
$ salary_estimate    &lt;chr&gt; "$53K-$91K (Glassdoor est.)", "$63K-$112K (Glassdoo…
$ job_description    &lt;chr&gt; "Data Scientist\nLocation: Albuquerque, NM\nEducati…
$ rating             &lt;dbl&gt; 3.8, 3.4, 4.8, 3.8, 2.9, 3.4, 4.1, 3.8, 3.3, 4.6, 3…
$ company_name       &lt;chr&gt; "Tecolote Research\n3.8", "University of Maryland M…
$ location           &lt;chr&gt; "Albuquerque, NM", "Linthicum, MD", "Clearwater, FL…
$ headquarters       &lt;chr&gt; "Goleta, CA", "Baltimore, MD", "Clearwater, FL", "R…
$ size               &lt;chr&gt; "501 - 1000", "10000+", "501 - 1000", "1001 - 5000"…
$ founded            &lt;dbl&gt; 1973, 1984, 2010, 1965, 1998, 2000, 2008, 2005, 201…
$ type_of_ownership  &lt;chr&gt; "Company - Private", "Other Organization", "Company…
$ industry           &lt;chr&gt; "Aerospace &amp; Defense", "Health Care Services &amp; Hosp…
$ sector             &lt;chr&gt; "Aerospace &amp; Defense", "Health Care", "Business Ser…
$ revenue            &lt;chr&gt; "$50 to $100 million (USD)", "$2 to $5 billion (USD…
$ competitors        &lt;chr&gt; "-1", "-1", "-1", "Oak Ridge National Laboratory, N…
$ hourly             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ employer_provided  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ lower_salary       &lt;dbl&gt; 53, 63, 80, 56, 86, 71, 54, 86, 38, 120, 126, 64, 1…
$ upper_salary       &lt;dbl&gt; 91, 112, 90, 97, 143, 119, 93, 142, 84, 160, 201, 1…
$ avg_salary_k       &lt;dbl&gt; 72.0, 87.5, 85.0, 76.5, 114.5, 95.0, 73.5, 114.0, 6…
$ company_txt        &lt;chr&gt; "Tecolote Research", "University of Maryland Medica…
$ job_location       &lt;chr&gt; "NM", "MD", "FL", "WA", "NY", "TX", "MD", "CA", "NY…
$ age                &lt;dbl&gt; 48, 37, 11, 56, 23, 21, 13, 16, 7, 12, 10, 53, 59, …
$ python             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, …
$ spark              &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, …
$ aws                &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, …
$ excel              &lt;dbl&gt; 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, …
$ sql                &lt;dbl&gt; 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, …
$ sas                &lt;dbl&gt; 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ keras              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ pytorch            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ scikit             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ tensor             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
$ hadoop             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, …
$ tableau            &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …
$ bi                 &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …
$ flink              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ mongo              &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ google_an          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ job_title_sim      &lt;chr&gt; "data scientist", "data scientist", "data scientist…
$ seniority_by_title &lt;chr&gt; "na", "na", "na", "na", "na", "na", "na", "na", "na…
$ degree             &lt;chr&gt; "M", "M", "M", "na", "na", "na", "na", "M", "P", "n…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     index        job_title         salary_estimate    job_description   
 Min.   :  0.0   Length:742         Length:742         Length:742        
 1st Qu.:221.5   Class :character   Class :character   Class :character  
 Median :472.5   Mode  :character   Mode  :character   Mode  :character  
 Mean   :469.1                                                           
 3rd Qu.:707.8                                                           
 Max.   :955.0                                                           
     rating       company_name         location         headquarters      
 Min.   :-1.000   Length:742         Length:742         Length:742        
 1st Qu.: 3.300   Class :character   Class :character   Class :character  
 Median : 3.700   Mode  :character   Mode  :character   Mode  :character  
 Mean   : 3.619                                                           
 3rd Qu.: 4.000                                                           
 Max.   : 5.000                                                           
     size              founded     type_of_ownership    industry        
 Length:742         Min.   :  -1   Length:742         Length:742        
 Class :character   1st Qu.:1939   Class :character   Class :character  
 Mode  :character   Median :1988   Mode  :character   Mode  :character  
                    Mean   :1837                                        
                    3rd Qu.:2007                                        
                    Max.   :2019                                        
    sector            revenue          competitors            hourly       
 Length:742         Length:742         Length:742         Min.   :0.00000  
 Class :character   Class :character   Class :character   1st Qu.:0.00000  
 Mode  :character   Mode  :character   Mode  :character   Median :0.00000  
                                                          Mean   :0.03235  
                                                          3rd Qu.:0.00000  
                                                          Max.   :1.00000  
 employer_provided  lower_salary     upper_salary    avg_salary_k  
 Min.   :0.00000   Min.   : 15.00   Min.   : 16.0   Min.   : 15.5  
 1st Qu.:0.00000   1st Qu.: 52.00   1st Qu.: 96.0   1st Qu.: 73.5  
 Median :0.00000   Median : 69.50   Median :124.0   Median : 97.5  
 Mean   :0.02291   Mean   : 74.75   Mean   :128.2   Mean   :101.5  
 3rd Qu.:0.00000   3rd Qu.: 91.00   3rd Qu.:155.0   3rd Qu.:122.5  
 Max.   :1.00000   Max.   :202.00   Max.   :306.0   Max.   :254.0  
 company_txt        job_location            age             python      
 Length:742         Length:742         Min.   : -1.00   Min.   :0.0000  
 Class :character   Class :character   1st Qu.: 12.00   1st Qu.:0.0000  
 Mode  :character   Mode  :character   Median : 25.00   Median :1.0000  
                                       Mean   : 47.52   Mean   :0.5283  
                                       3rd Qu.: 60.00   3rd Qu.:1.0000  
                                       Max.   :277.00   Max.   :1.0000  
     spark             aws             excel             sql        
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.0000   Median :0.0000   Median :1.0000   Median :1.0000  
 Mean   :0.2251   Mean   :0.2372   Mean   :0.5229   Mean   :0.5121  
 3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
      sas              keras            pytorch            scikit       
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000  
 Median :0.00000   Median :0.00000   Median :0.00000   Median :0.00000  
 Mean   :0.08895   Mean   :0.03908   Mean   :0.05256   Mean   :0.07278  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000   Max.   :1.00000  
     tensor            hadoop          tableau             bi         
 Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median :0.00000   Median :0.0000   Median :0.0000   Median :0.00000  
 Mean   :0.09704   Mean   :0.1671   Mean   :0.1995   Mean   :0.07547  
 3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :1.00000   Max.   :1.0000   Max.   :1.0000   Max.   :1.00000  
     flink             mongo           google_an       job_title_sim     
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000   Length:742        
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000   Class :character  
 Median :0.00000   Median :0.00000   Median :0.00000   Mode  :character  
 Mean   :0.01348   Mean   :0.04987   Mean   :0.01887                     
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000                     
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000                     
 seniority_by_title    degree         
 Length:742         Length:742        
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(kg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 742  42</code></pre>
</div>
</div>
</section>
<section id="data-quality-issues" class="level1">
<h1><strong>Data quality issues</strong></h1>
<p>Several variables contain placeholder values that represent missing data rather than valid observations. For example, <code>Rating</code>, <code>Founded</code>, and <code>Age</code> include values of <code>-1</code>, while variables such as <code>Competitors</code>, <code>seniority_by_title</code>, and <code>Degree</code> use strings such as <code>"-1"</code> or <code>"na"</code> to indicate unavailable information. These values must be recoded as missing before further analysis.</p>
<section id="summary-of-the-initial-inspection" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-the-initial-inspection"><strong>Summary of the initial inspection</strong></h2>
<p>The dataset contains 742 job postings and 42 variables. These variables include job and company descriptors, salary information, and binary indicators for technical skills such as Python, SQL, AWS, and Tableau. Initial inspection using <code>glimpse()</code> and <code>summary()</code> showed that the dataset contains both raw text variables and derived variables that are more suitable for analysis.</p>
</section>
<section id="skill-demand" class="level2">
<h2 class="anchored" data-anchor-id="skill-demand"><strong>Skill demand</strong></h2>
<p>The binary skill columns provide a practical proxy for skill demand in job postings. Since these variables are coded as 0 and 1, their means can be interpreted as the proportion of postings that require each skill. Preliminary results suggest that Python, Excel, and SQL are among the most frequently requested skills in the dataset.</p>
</section>
<section id="outliers-and-unusual-values" class="level2">
<h2 class="anchored" data-anchor-id="outliers-and-unusual-values"><strong>Outliers and unusual values</strong></h2>
<p>Exploratory summaries also suggest the presence of extreme values. For instance, company age ranges up to 277 years, and average salary ranges from 15.5 to 254 thousand dollars. While some of these values may be valid, they require further inspection through visualizations such as boxplots and histograms.</p>
</section>
<section id="re-coding-placeholder-values-as-missing" class="level2">
<h2 class="anchored" data-anchor-id="re-coding-placeholder-values-as-missing"><strong>#Re-coding placeholder values as missing</strong></h2>
<p><strong>Standardize Kaggle jobs</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>kaggle_jobs <span class="ot">&lt;-</span> kg <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">job_id =</span> <span class="fu">paste0</span>(<span class="st">"kg_"</span>, <span class="fu">row_number</span>()),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">source =</span> <span class="st">"kaggle"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    job_title,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">company =</span> company_name,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    location,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    industry,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    avg_salary_k,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">salary_min_k =</span> lower_salary,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">salary_max_k =</span> upper_salary,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    job_description,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">job_url =</span> <span class="cn">NA_character_</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>kaggle_jobs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 742 × 11
   job_id source job_title   company location industry avg_salary_k salary_min_k
   &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
 1 kg_1   kaggle Data Scien… "Tecol… Albuque… Aerospa…         72             53
 2 kg_2   kaggle Healthcare… "Unive… Linthic… Health …         87.5           63
 3 kg_3   kaggle Data Scien… "KnowB… Clearwa… Securit…         85             80
 4 kg_4   kaggle Data Scien… "PNNL\… Richlan… Energy           76.5           56
 5 kg_5   kaggle Data Scien… "Affin… New Yor… Adverti…        114.            86
 6 kg_6   kaggle Data Scien… "Cyrus… Dallas,… Real Es…         95             71
 7 kg_7   kaggle Data Scien… "Clear… Baltimo… Banks &amp;…         73.5           54
 8 kg_8   kaggle Data Scien… "Logic… San Jos… Consult…        114             86
 9 kg_9   kaggle Research S… "Roche… Rochest… Health …         61             38
10 kg_10  kaggle Data Scien… "&lt;inte… New Yor… Internet        140            120
# ℹ 732 more rows
# ℹ 3 more variables: salary_max_k &lt;dbl&gt;, job_description &lt;chr&gt;, job_url &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="standardize-builtin-jobs" class="level2">
<h2 class="anchored" data-anchor-id="standardize-builtin-jobs">Standardize BuiltIn jobs</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>builtin_jobs_clean <span class="ot">&lt;-</span> builtin_jobs <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">job_id =</span> <span class="fu">paste0</span>(<span class="st">"bi_"</span>, <span class="fu">row_number</span>()),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">source =</span> <span class="st">"builtin"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    job_title,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    company,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">location =</span> <span class="cn">NA_character_</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    industry,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_salary_k =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">salary_min_k =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">salary_max_k =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    job_description,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    job_url</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>builtin_jobs_clean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 11
   job_id source  job_title  company location industry avg_salary_k salary_min_k
   &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
 1 bi_1   builtin Manager, … &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
 2 bi_2   builtin Principal… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
 3 bi_3   builtin Principal… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
 4 bi_4   builtin Senior As… NY Life &lt;NA&gt;     Finance            NA           NA
 5 bi_5   builtin Data Scie… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
 6 bi_6   builtin Staff Dat… Grow T… &lt;NA&gt;     Healthc…           NA           NA
 7 bi_7   builtin Senior St… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
 8 bi_8   builtin Staff Dat… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
 9 bi_9   builtin Forward-D… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
10 bi_10  builtin AI &amp; GenA… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
11 bi_11  builtin Data Scie… &lt;NA&gt;    &lt;NA&gt;     &lt;NA&gt;               NA           NA
# ℹ 3 more variables: salary_max_k &lt;dbl&gt;, job_description &lt;chr&gt;, job_url &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="merge-job-postings" class="level2">
<h2 class="anchored" data-anchor-id="merge-job-postings">Merge Job postings</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>all_jobs <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(kaggle_jobs, builtin_jobs_clean)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>all_jobs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 753 × 11
   job_id source job_title   company location industry avg_salary_k salary_min_k
   &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
 1 kg_1   kaggle Data Scien… "Tecol… Albuque… Aerospa…         72             53
 2 kg_2   kaggle Healthcare… "Unive… Linthic… Health …         87.5           63
 3 kg_3   kaggle Data Scien… "KnowB… Clearwa… Securit…         85             80
 4 kg_4   kaggle Data Scien… "PNNL\… Richlan… Energy           76.5           56
 5 kg_5   kaggle Data Scien… "Affin… New Yor… Adverti…        114.            86
 6 kg_6   kaggle Data Scien… "Cyrus… Dallas,… Real Es…         95             71
 7 kg_7   kaggle Data Scien… "Clear… Baltimo… Banks &amp;…         73.5           54
 8 kg_8   kaggle Data Scien… "Logic… San Jos… Consult…        114             86
 9 kg_9   kaggle Research S… "Roche… Rochest… Health …         61             38
10 kg_10  kaggle Data Scien… "&lt;inte… New Yor… Internet        140            120
# ℹ 743 more rows
# ℹ 3 more variables: salary_max_k &lt;dbl&gt;, job_description &lt;chr&gt;, job_url &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values"><strong>Missing Values</strong></h2>
<p>Missing values were identified using the <code>is.na()</code> function. Depending on the variable, missing values were either removed or handled appropriately to maintain data integrit</p>
</section>
<section id="merge-kaggle-skills" class="level2">
<h2 class="anchored" data-anchor-id="merge-kaggle-skills"><strong>Merge kaggle skills</strong></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>skill_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(kg)[</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(kg) <span class="sc">%in%</span> <span class="fu">c</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"python"</span>,<span class="st">"sql"</span>,<span class="st">"aws"</span>,<span class="st">"excel"</span>,<span class="st">"tableau"</span>,<span class="st">"spark"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sas"</span>,<span class="st">"pytorch"</span>,<span class="st">"keras"</span>,<span class="st">"scikit"</span>,<span class="st">"tensor"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"hadoop"</span>,<span class="st">"flink"</span>,<span class="st">"mongo"</span>,<span class="st">"google_an"</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>kaggle_job_skills <span class="ot">&lt;-</span> kg <span class="sc">|&gt;</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">job_id =</span> <span class="fu">paste0</span>(<span class="st">"kg_"</span>, <span class="fu">row_number</span>())) <span class="sc">|&gt;</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(job_id, <span class="fu">all_of</span>(skill_cols)) <span class="sc">|&gt;</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span>job_id,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"skill"</span>,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"present"</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(present <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(job_id, skill)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>#Summarizing the skills we can see that python, excel and sql are the most required skill in the job market</p>
<p><strong>#BuiltIn skills</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>skill_keywords <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"python"</span>,<span class="st">"r"</span>,<span class="st">"sql"</span>,<span class="st">"scala"</span>,<span class="st">"java"</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pytorch"</span>,<span class="st">"tensorflow"</span>,<span class="st">"scikit"</span>,<span class="st">"sklearn"</span>,<span class="st">"xgboost"</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"aws"</span>,<span class="st">"azure"</span>,<span class="st">"gcp"</span>,<span class="st">"databricks"</span>,<span class="st">"snowflake"</span>,<span class="st">"spark"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tableau"</span>,<span class="st">"power bi"</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>builtin_job_skills_clean <span class="ot">&lt;-</span> builtin_jobs <span class="sc">|&gt;</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">job_id =</span> <span class="fu">paste0</span>(<span class="st">"bi_"</span>, <span class="fu">row_number</span>())) <span class="sc">|&gt;</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(job_id, <span class="at">text =</span> <span class="fu">tolower</span>(<span class="fu">coalesce</span>(job_description, <span class="st">""</span>))) <span class="sc">|&gt;</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">nzchar</span>(text)) <span class="sc">|&gt;</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">crossing</span>(<span class="at">skill =</span> skill_keywords) <span class="sc">|&gt;</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rx =</span> <span class="fu">paste0</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">b"</span>, skill, <span class="st">"</span><span class="sc">\\</span><span class="st">b"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(text, <span class="fu">regex</span>(rx, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(job_id, skill)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>####Merge all skills</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>all_job_skills <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  kaggle_job_skills,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  builtin_job_skills_clean</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>all_job_skills</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,142 × 2
   job_id skill  
   &lt;chr&gt;  &lt;chr&gt;  
 1 kg_1   python 
 2 kg_1   excel  
 3 kg_1   sas    
 4 kg_1   tableau
 5 kg_2   python 
 6 kg_3   python 
 7 kg_3   spark  
 8 kg_3   excel  
 9 kg_3   sql    
10 kg_3   sas    
# ℹ 2,132 more rows</code></pre>
</div>
</div>
<p><strong>##Checks</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(all_jobs, source)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  source      n
  &lt;chr&gt;   &lt;int&gt;
1 builtin    11
2 kaggle    742</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(all_job_skills, skill, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 2
   skill       n
   &lt;chr&gt;   &lt;int&gt;
 1 python    402
 2 sql       389
 3 excel     388
 4 aws       183
 5 spark     170
 6 tableau   150
 7 hadoop    124
 8 tensor     72
 9 sas        66
10 scikit     55
# ℹ 13 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(all_jobs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 753
Columns: 11
$ job_id          &lt;chr&gt; "kg_1", "kg_2", "kg_3", "kg_4", "kg_5", "kg_6", "kg_7"…
$ source          &lt;chr&gt; "kaggle", "kaggle", "kaggle", "kaggle", "kaggle", "kag…
$ job_title       &lt;chr&gt; "Data Scientist", "Healthcare Data Scientist", "Data S…
$ company         &lt;chr&gt; "Tecolote Research\n3.8", "University of Maryland Medi…
$ location        &lt;chr&gt; "Albuquerque, NM", "Linthicum, MD", "Clearwater, FL", …
$ industry        &lt;chr&gt; "Aerospace &amp; Defense", "Health Care Services &amp; Hospita…
$ avg_salary_k    &lt;dbl&gt; 72.0, 87.5, 85.0, 76.5, 114.5, 95.0, 73.5, 114.0, 61.0…
$ salary_min_k    &lt;dbl&gt; 53, 63, 80, 56, 86, 71, 54, 86, 38, 120, 126, 64, 106,…
$ salary_max_k    &lt;dbl&gt; 91, 112, 90, 97, 143, 119, 93, 142, 84, 160, 201, 106,…
$ job_description &lt;chr&gt; "Data Scientist\nLocation: Albuquerque, NM\nEducation …
$ job_url         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(all_job_skills)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,142
Columns: 2
$ job_id &lt;chr&gt; "kg_1", "kg_1", "kg_1", "kg_1", "kg_2", "kg_3", "kg_3", "kg_3",…
$ skill  &lt;chr&gt; "python", "excel", "sas", "tableau", "python", "python", "spark…</code></pre>
</div>
</div>
<p>##Kaggle Frequency of skills in job postings</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>skill_counts <span class="ot">&lt;-</span> kaggle_job_skills <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(skill, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(skill_counts, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(skill, n), <span class="at">y =</span> n, <span class="at">fill =</span> skill )) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Frequency of Skills in Job Postings"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Skill"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of postings"</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Code-Analysis-P3_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>##BuiltIn frequency of skills in job postings</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>skill_counts <span class="ot">&lt;-</span> builtin_job_skills_clean <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(skill, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(skill_counts, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(skill, n), <span class="at">y =</span> n, <span class="at">fill =</span> skill )) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Frequency of Skills in Job Postings"</span>,</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Skill"</span>,</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of postings"</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Code-Analysis-P3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="number-of-jobs-posting-vs-average-salary" class="level2">
<h2 class="anchored" data-anchor-id="number-of-jobs-posting-vs-average-salary"><strong>Number of jobs posting vs Average Salary</strong></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>all_jobs_salary <span class="ot">&lt;-</span> all_jobs <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(avg_salary_k))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(all_jobs_salary, <span class="fu">aes</span>(<span class="at">x =</span> avg_salary_k)) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Average Salary"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Average Salary (K)"</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Job Postings"</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Code-Analysis-P3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>##Interpretation</strong></p>
<p>The histogram shows that most job postings fall within the mid-range salary band, with a concentration between approximately 70K and 130K. Higher salary values are less frequent and may represent senior or specialized roles.</p>
</section>
<section id="check-salary-outliers" class="level2">
<h2 class="anchored" data-anchor-id="check-salary-outliers"><strong>Check salary Outliers</strong></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(all_jobs_salary, <span class="fu">aes</span>(<span class="at">y =</span> avg_salary_k)) <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplot of Average Salary"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Salary (K)"</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Code-Analysis-P3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>##The Average Salary is 70k to 125k after observing the boxplot</p>
<section id="check-job-title-and-salary" class="level3">
<h3 class="anchored" data-anchor-id="check-job-title-and-salary"><strong>Check job title and salary</strong></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>job_salary_summary <span class="ot">&lt;-</span> all_jobs_salary <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(job_title) <span class="sc">|&gt;</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_salary =</span> <span class="fu">mean</span>(avg_salary_k, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_salary =</span> <span class="fu">median</span>(avg_salary_k, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_salary))</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>job_salary_summary <span class="sc">|&gt;</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>( <span class="at">x =</span> <span class="fu">reorder</span>(job_title, mean_salary), <span class="at">y =</span> mean_salary, <span class="at">fill =</span> job_title)) <span class="sc">+</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Salary for Job Title"</span>,</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Job Title"</span>,</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">" Average Salary (K)"</span></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Code-Analysis-P3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>##To compare pay across roles, job postings were grouped by job title and summarized using average salary. Because many titles appeared only a few times, the analysis focused on titles with at least five postings. This provides a more stable comparison of salary levels across common job categories.</p>
<p>##Comparing kaggle vs BuiltIn skills</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>source_skill_counts <span class="ot">&lt;-</span> all_jobs <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(all_job_skills, <span class="at">by =</span> <span class="st">"job_id"</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(skill)) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(source, skill)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>source_skill_counts <span class="sc">|&gt;</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(skill, n), <span class="at">y =</span> n, <span class="at">fill =</span> source)) <span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Skill Frequency by Data Source"</span>,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Skill"</span>,</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Job Postings"</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Code-Analysis-P3_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>